# Generated by Django 5.1.4 on 2024-12-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
