# Generated by Django 5.1.4 on 2024-12-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('workouts', '0002_workouttemplate_profile_alter_workouttemplate_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateExercise',
            new_name='Exercise',
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('repetition_schedule', models.CharField(blank=True, max_length=50)),
                ('exercises', models.ManyToManyField(blank=True, to='workouts.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutTemplate',
        ),
    ]
