# Generated by Django 5.1.4 on 2024-12-24 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_templateexercise_exercise_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='repetition_schedule',
        ),
        migrations.AddField(
            model_name='workout',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='performed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
