# Generated by Django 5.1.4 on 2024-12-25 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workout_repetition_schedule_workout_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='performed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
