# Generated by Django 5.1.4 on 2024-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workout_performed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('warmup', 'Warmup'), ('cooldown', 'Cooldown'), ('failure', 'Failure'), ('dropset', 'Dropset')], default='normal', max_length=50),
        ),
    ]
