# Generated by Django 5.1.4 on 2024-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_set_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='tags',
            field=models.ManyToManyField(blank=True, to='workouts.settag'),
        ),
    ]
