# Generated by Django 5.1.4 on 2024-12-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_set_options_set_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
