# Generated by Django 5.1.4 on 2024-12-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_set_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='workouts.exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='sets', to='workouts.set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='tags',
            field=models.ManyToManyField(blank=True, to='workouts.settag'),
        ),
    ]
