# Generated by Django 5.1.4 on 2025-01-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_set_exercise_alter_exercise_sets_alter_set_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='type',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Warmup'), ('C', 'Cooldown'), ('F', 'Failure'), ('D', 'Dropset')], default='N', max_length=50),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition_schedule', models.CharField(blank=True, max_length=50)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
    ]
