# Generated by Django 5.1.4 on 2025-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_set_type_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='repetition_schedule',
        ),
        migrations.AddField(
            model_name='template',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='schedule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'biweekly')], max_length=50),
        ),
    ]
