# Generated by Django 5.1.4 on 2025-01-03 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_remove_template_repetition_schedule_template_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='performed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
