# Generated by Django 5.1.4 on 2025-01-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_alter_workout_performed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-performed_date']},
        ),
    ]
