# Generated by Django 5.1.4 on 2025-01-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_template_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='WorkoutExercise',
        ),
    ]
