# Generated by Django 5.1.4 on 2025-01-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0017_rename_exercise_workoutexercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("estimated_1rm", models.FloatField()),
                ("max_vol", models.FloatField()),
                ("max_weight", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="name",
        ),
        migrations.AlterField(
            model_name="set",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_exercise",
                to="workouts.workoutexercise",
            ),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise",
                to="workouts.exercise",
            ),
            preserve_default=False,
        ),
    ]
