# Generated by Django 5.1.4 on 2025-01-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0018_exercise_remove_workoutexercise_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="estimated_1rm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="max_vol",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="max_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
