# Generated by Django 5.1.4 on 2025-01-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workouts",
            "0019_alter_exercise_estimated_1rm_alter_exercise_max_vol_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="body_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("core", "Core"),
                    ("arms", "Arms"),
                    ("back", "Back"),
                    ("chest", "Chest"),
                    ("legs", "Legs"),
                    ("shoulders", "Shoulders"),
                    ("other", "Other"),
                    ("olympic", "Olympic"),
                    ("full_body", "Full body"),
                    ("cardio", "Cardio"),
                ],
                null=True,
            ),
        ),
    ]
