# Generated by Django 5.1.4 on 2025-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0020_exercise_body_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="body_part",
            field=models.CharField(
                choices=[
                    ("core", "Core"),
                    ("arms", "Arms"),
                    ("back", "Back"),
                    ("chest", "Chest"),
                    ("legs", "Legs"),
                    ("shoulders", "Shoulders"),
                    ("other", "Other"),
                    ("olympic", "Olympic"),
                    ("full_body", "Full body"),
                    ("cardio", "Cardio"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
