# Generated by Django 5.1.4 on 2025-01-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0023_remove_set_note_workoutexercise_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
