# Generated by Django 5.1.4 on 2025-02-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0024_workout_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_custom",
            field=models.BooleanField(default=True),
        ),
    ]
