# Generated by Django 5.1.4 on 2025-02-01 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_measurement_is_favorite"),
        ("workouts", "0025_exercise_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
