# Generated by Django 5.1.4 on 2025-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0026_exercise_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="prs_achieved",
            field=models.IntegerField(default=0),
        ),
    ]
