# Generated by Django 5.1.4 on 2025-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0027_workout_prs_achieved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=9,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="template",
            name="day",
        ),
        migrations.AddField(
            model_name="template",
            name="days",
            field=models.ManyToManyField(blank=True, to="workouts.day"),
        ),
    ]
