# Generated by Django 5.1.4 on 2025-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0029_alter_day_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="reps_or_duration",
            field=models.CharField(
                choices=[("reps", "Reps"), ("duration", "Duration")],
                default="reps",
                max_length=8,
            ),
        ),
    ]
