# Generated by Django 5.1.4 on 2025-02-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0030_workoutexercise_reps_or_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
