# Generated by Django 5.1.4 on 2025-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0031_set_duration_alter_set_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, choices=[("kg", "kg"), ("lb", "lb")], max_length=5
                    ),
                ),
                ("value", models.FloatField()),
            ],
        ),
    ]
