# Generated by Django 5.1.4 on 2025-02-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0032_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workouts.weight",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workouts.weight",
            ),
        ),
    ]
