# Generated by Django 5.1.4 on 2025-02-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0033_alter_set_weight_alter_workout_volume"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Weight",
            new_name="UnitValue",
        ),
    ]
