# Generated by Django 5.1.4 on 2025-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0034_rename_weight_unitvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitvalue",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("kg", "kg"), ("lb", "lb"), ("kcal", "kcal"), ("cm", "cm")],
                max_length=5,
            ),
        ),
    ]
