# Generated by Django 5.1.4 on 2025-01-06 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_measurement_date"),
        ("workouts", "0022_remove_exercise_estimated_1rm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_1rm", models.FloatField(blank=True, null=True)),
                ("max_vol", models.FloatField(blank=True, null=True)),
                ("max_weight", models.FloatField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_stats_exercise",
                        to="workouts.exercise",
                    ),
                ),
            ],
        ),
    ]
