# Generated by Django 5.1.4 on 2025-01-26 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_exercisestats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="date",
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="value",
        ),
        migrations.AlterField(
            model_name="measurement",
            name="label",
            field=models.CharField(
                choices=[
                    ("weight", "Weight"),
                    ("calories", "Calories"),
                    ("body_fat", "Body Fat"),
                    ("neck", "Neck"),
                    ("shoulders", "Shoulders"),
                    ("chest", "Chest"),
                    ("waist", "Waist"),
                    ("hips", "Hips"),
                    ("left_bicep", "Left Bicep"),
                    ("right_bicep", "Right Bicep"),
                    ("left_forearm", "Left Forearm"),
                    ("right_forearm", "Right Forearm"),
                    ("upper_abs", "Upper Abs"),
                    ("lower_abs", "Lower Abs"),
                    ("left_thigh", "Left Thigh"),
                    ("right_thigh", "Right Thigh"),
                    ("left_calf", "Left Calf"),
                    ("right_calf", "Right Calf"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MeasurementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=5)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_record",
                        to="users.measurement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measurement",
            name="records",
            field=models.ManyToManyField(
                blank=True,
                related_name="measurement_records",
                to="users.measurementrecord",
            ),
        ),
    ]
