# Generated by Django 5.1.4 on 2025-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_measurement_date_remove_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
