# Generated by Django 5.1.4 on 2025-02-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_use_kg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurementrecord",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="measurementrecord",
            name="value",
        ),
    ]
