# Generated by Django 5.1.4 on 2025-02-17 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_measurementrecord_unit_and_more"),
        ("workouts", "0034_rename_weight_unitvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementrecord",
            name="value",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurement_record_value",
                to="workouts.unitvalue",
            ),
            preserve_default=False,
        ),
    ]
