# Generated by Django 5.1.4 on 2025-02-18 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_exercisestats_estimated_1rm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisestats",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_stats_profile",
                to="users.profile",
            ),
            preserve_default=False,
        ),
    ]
