# Generated by Django 5.1.4 on 2025-02-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_tutorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tutorials",
            field=models.ManyToManyField(blank=True, to="users.tutorial"),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
