# Generated by Django 5.1.4 on 2025-02-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_profile_tutorials_alter_tutorial_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="tutorials",
        ),
        migrations.DeleteModel(
            name="Tutorial",
        ),
    ]
